### ISSUE TITLE
Rewrite of player Skill System

### ISSUE THREAD

**Issue by blacksnotling** [blacksnotling/HDWSBBL#198]
Existing table
The match player table will no longer need the inc and skill fields

Logic flow
Admin
Manage Player (Post CPT conversion) the ability to add or edit the Skills assigned. Current skills can be removed (with SPP refunded), and new skills can be added using the logic from add match player (2) below. Uses AJAX(!)
Add Match - No Change
Add Match Player (1) - check box for injuries and skill
Add Match player (2) - total rewrite!
* Only displays the players who had a check box for injury of skill
* For injuries a Drop down is selected with all possible injuries (both normal and Stunty - check rulebook)
* Option for N/A in the event of accidentally selected, or not relevant
* For Skills, it will count how many they already have, and present the next valid options (e.g, if they have 3 skills, it only shows the options and costs for the 4th skill)
Upon submission
Injuries
* Increase player table is updated - player ID, Match, Injury ID, type (lookup against the increase table)
* Player is updated (MNG flag, Cost Next Game, stat change (if needed)
* Team is updated (Current TV)
Skills
* Increase player table is updates - player ID, match, Skill ID, type (lookup against the increase table)
* Player is updated (Cost, Cost NG, Stat change (if needed) - HOW?
* Team is updated (Current TV)

Front end
Roster
* Player Skills - select all skills from player increase table and output, select all injuries which should be listed on a roster from player increase table and output. Might be able to filter on type. Legacy teams remain unchanged
View Player
* Player Rank - counts the number of skills in the player increase table, switch case to determine “level” Legacy teams remain unchanged
* Match history - Remove injuries and increases from display. Have a new table which lists them in chronological order. This can be grabbed straight from the player increase table, and solves the problem of the table being too wide! Legacy teams remain unchanged
* Player Stats as per the roster Legacy teams remain unchanged
View Match
* Player Increases - pulled straight from the player increase table, matched on match_ID. Legacy teams remain unchanged
* Player Injuries - pulled straight from the player increase table, matched on match_ID. Legacy teams remain unchanged

Player Increase Table
Injury list
Skill list
Increase table - to determine if an increase is an injury or Increase (bool), plus the SPP cost, and if it has a stat change, and if it causes a MNG)

Player Increase Table
P_ID (WPID BIGINT 20) - index
M_ID (WPID BIGINT 20) - index
skill_ID (BIGINT 20 - lookup against the Skill table)
Inj_ID (BIGINT 20 - lookup against the Injury table)
Inc_ID (lookup against the Increase table) - used to perform a lookup so the cost can be displayed on the player page, and on the roster for cost breakdown

Key is P_IDm M_ID and INC_ID (as the player might get more than one entry per match)

Increase Table
Inc ID (BIGINT 20) Unique Key
inc_type (bool) - injury or skill
inc_spp - the SPP cost of the increase - what will be deducted
inc_cost - the cost of the increase (change to player cost)

Skills
Skill_ID (big int 20) - unique
Skill_name (Varchar 20)
Skill_Cat_ID (BIGINT 20) lookup against skills_cat table
Skill_Stat (the stat that is changed) - this will be displayed on the site so is needed here
Skill_Legacy (bool, default 0) for older skills when I finally convert them!) - so their display can be suppressed from the admin screen, but old records can be displayed correctly

Skills_cat
Skill_cat_ID (bigint 20) - Unique
Skill_cat_name (VARCHAR 20)

Injuries
inj_ID (BIGINT 20) - Unique
INJ_name (VARCHAR 20)
inj_MNG (bool)
Inj_Stat (the stat that is changed) - this will be displayed on the site so is needed here

Example to run through code
Player A gets their second skill during a match
It is a random primary (4spp) and will increase their value by 10,000gp

* Player_inc table
* Match X, Player X, Skilll 7 (block), Inc 0, Type 7

* Referenced
* Match, player, and skill tables are straight lookups
* Inc table. 7 is a tier 2, 10,000 increase, and costs 4 SPP

* Player table is updated. Cost and Cost NG is increased by 10,000, and 4 SPP are removed

Player A then gets injured during the next game - no long term effect ( no MNG)

* Match X, Player X, Skilll 0, Inj 43 (Badly hurt), inc_id 0, 

* Referenced
* Match and player are straight lookups
* Injury table confirms no MNG or stat removal

* Player table is updated. MNG is 0, Cost NG remains unchanged

Player A then gets injured again - broken back (or whatever) . Result is -ST

* Match X, Player X, Skilll 0, Inj 77 (Broken Back), inc_id 0, 

* Referenced
* Match and player are straight lookups
* Injury table confirms MNG, and ST are impacted

* Player table is updated. MNG is 1, Cost NG is set to zero, and ST stat is reduced by 1

Player A finally gets their 3rd skill, a ST increase

* Player_inc table
* Match X, Player X, Skilll 99 (+ST), Inc 0, Type 10

* Referenced
* Match, player, and skill tables are straight lookups
* Inc table. 10 is a tier 3, 40,000 increase, and costs X SPP
* Skill table indicates that a stat is attached (ST)

* Player table is updated. Cost and Cost NG is increased by 40,000, X SPP are removed, and Stat (ST) is increased

On the player increase history it will list
Match X - Block +10000
Match X - Badly Hurt
Match X - Broken Back -ST
Match X - +ST +40,000

All data can be grabbed from looking up the player_inc table, and joining the skill and injury tables.
IF SPP is needed then a join to the increase table is needed as the value is stored there

If I edit the player record to remove the skill, then it needs to lookup the Inc Type to see how much value is changed, SPP are refunded, and what st is reduced

Questions
* When displaying, how the does the site know if to list the injury in the player stats ./ roster? We don’t want all badly hurt, no long term effects to be lists
* Should we differentiate on injuries between stunts and others (is there a difference apart from stat capture that they were a stunty?
* Is the increase table used for adding to the database rather than displaying? If so make sure nothing is in there that is needed to display., If this means adding _ST to the skills table then that is fine)

**Comment by blacksnotling** [comment]
Tasks

- [x] Create new Database Tables
- [x] Populate New Database Tables
- [x] Create functions to generate injuries / skills lists
- [x] Modify add match player (1) and (2)
- [x] Update the function that restores the player from MNG to take into account how costs of skills are stored 
- [x] Edit JavaScript from add match Player for new SPP thresholds https://github.com/blacksnotling/HDWSBBL/issues/192
- [x] Update View Match
- [x] Update View player
- [x] Make sure Players titles are correct https://github.com/blacksnotling/HDWSBBL/issues/157
- [x] Update Roster
- [x] Make sure changes to stats are highlighted https://github.com/blacksnotling/HDWSBBL/issues/60
- [x] Manage Player (post CPT Conversion)

**Comment by blacksnotling** [comment]
[198.txt](https://github.com/blacksnotling/HDWSBBL/files/7493106/198.txt)
SQL file to generate the new tables and default entries

**Comment by blacksnotling** [comment]
Insert Updated SQL here!

**Comment by blacksnotling** [comment]
[skills_rewritesql.txt](https://github.com/blacksnotling/HDWSBBL/files/8535332/skills_rewritesql.txt)
Updated SQL File

**Comment by blacksnotling** [comment]
Done here: https://github.com/blacksnotling/HDWSBBL/commit/ccce6a6607ef2f40487a78cefb240bd49c34e9b8
